---
- hosts: localhost
  roles:
    - role: dashboard
      disabled: YES
    - role: dotfiles
    - role: vim

  tasks:
    # fonts
    - homebrew_tap: name=caskroom/fonts

    - homebrew: name={{ item }} state=latest
      with_items:
        # dev
        - git
        - git-extras
        - cloc
        - jq
        - siege
        - the_silver_searcher
        - xctool
        - docker
        - boot2docker
        ## language
        - rbenv
        - ruby-build
        - rbenv-gem-rehash
        - rbenv-vars
        - nvm

        # music
        - flac
        - lame

        # tool
        - hub
        - aria2
        - graphviz
        - imagemagick
        - unrar
        - p7zip
        - lftp
        - mtr
        - watch

        # shell
        - zsh
        - zsh-completions
        - autojump
        - pstree
        - tmux
        - tree

        # other
        - fortune

    - homebrew_cask: name={{ item }}
      with_items:
        - aliwangwang
        - appcleaner
        - calibre
        - colloquy
        - colorpicker-developer
        - dash
        - diffmerge
        - evernote
        - filezilla
        - flux
        - gas-mask
        - gitx
        - google-chrome
        - grandperspective
        - hipchat
        - icefloor
        - ifunbox
        - iterm2
        - lastfm
        - liteicon
        - macdown
        - marked
        - nethackcocoa
        - nvalt
        - openemu
        - qq
        - racket
        - ringtones
        - sequel-pro
        - shiori
        - sidestep
        - skim
        - skitch
        - spotify
        - sqlite-database-browser
        - steam
        - superduper
        - transmission
        - vagrant
        - virtualbox
        - vlc
        - vox-preference-pane
        - wechat
        - weibox
        - xiami
        - xld
