---
- hosts: all
  tasks:
    - group_by: key=${ansible_distribution}

- name: Get the source code of vim from official repo
  hosts: all
  user: kane
  vars_files:
    - vars/vim-latest_vars.yml
  tasks:
    - name: update repo
      hg: >
        repo=https://code.google.com/p/vim/ dest={{ local_repo }}
        revision={{ revision }}
      register: repo

- name: Install vim
  hosts:
    - Linuxmint
    - Debian
    - Ubuntu
  vars_files:
    - vars/vim-latest_vars.yml
  tasks:
    - name: remove distribution vim
      sudo: yes
      apt: pkg={{ item }} state=absent
      with_items:
        - vim
        - vim-runtime
        - gvim

    - name: install build deps
      sudo: yes
      apt: pkg={{ item }} state=latest
      with_items:
        - libncurses5-dev
        - libgnome2-dev
        - libgnomeui-dev
        - libgtk2.0-dev
        - libatk1.0-dev
        - libbonoboui2-dev
        - libcairo2-dev
        - libX11-dev
        - libxpm-dev
        - libxt-dev
        - python-dev
        - ruby-dev
        - mercurial
        - checkinstall

    - name: configure and build
      when: repo.changed
      shell: >
        chdir={{ local_repo }}
        ./configure --with-features=huge --enable-rubyinterp
        --enable-pythoninterp --enable-perlinterp --enable-gui=gtk2
        --enable-cscope --prefix=/usr
        &&
        make

    - name: install
      when: repo.changed
      sudo: yes
      command: checkinstall chdir={{ local_repo }}

    - name: set as default editor
      when: repo.changed
      sudo: yes
      shell: >
        update-alternatives --install /usr/bin/editor editor /usr/bin/vim 1 &&
        update-alternatives --set editor /usr/bin/vim;
        update-alternatives --install /usr/bin/vi vi /usr/bin/vim 1 &&
        update-alternatives --set vi /usr/bin/vim
