---
- hosts: work
  strategy: free
  become: yes
  vars:
    ansible_ssh_pipelining: no
  tasks:
    - lineinfile:
        dest: /etc/sudoers
        regexp: '^Defaults.*requiretty$'
        backrefs: yes
        state: absent
